export interface Project {
  id: string;
  slug: string;
  title: string;
  description: string;
  image: string;
  date: string;
  tags: string[];
  url: string;
  source: string;
  status: "published" | "draft";
}

export const projects: Project[] = [
  {
    id: "memory-map",
    slug: "memory-map",
    title: "IdeaForge — The AI Inspiration Forge",
    description: " Where raw sparks become forged products\n\n  Everyone has ideas. Few can turn them into something real. IdeaForge (AI灵感锻造炉) is a full-stack AI workshop that\n  walks anyone — no business training, no technical degree required — through the entire journey from a vague spark to a\n   complete, investable product plan.\n\n  ---\n  From \"what if\" to \"here it is\" — a four-stage forge\n\n  ① Sensing the real need.\n  Before a single solution is drawn, IdeaForge listens. It applies five rigorously engineered innovation methodologies —\n   TRIZ, JTBD, First Principles, Lateral Thinking, and SCAMPER — each with an advanced professional edition, to strip\n  away surface desires and expose the true, unmet need beneath. It scans existing products, names their limits, and\n  opens three or more defensible innovation directions.\n\n  ② Forging the first concept.\n  Your chosen direction is forged into a structured initial proposal: product positioning, core features, market\n  opportunity, technical path, and a go-to-market angle — clear enough to argue about, solid enough to build on.\n\n  ③ The council of five experts.\n  The proposal is placed before five uncompromising specialists: the Product Architect, the Market Analyst, the Tech\n  Lead, the UX/UI Director, and the Growth Hacker. Each delivers blunt, actionable critique — not flattery. You decide:\n  accept, edit, or reject each point, and set its priority.\n\n  ④ The final synthesis.\n  Only the opinions you chose are melted back into the furnace. Every accepted point is answered in a complete Business\n  Plan & Requirements Document — not vaguely, but as concrete design, architecture, and strategy. Where expert opinions\n  irreconcilably clash, the tool says so honestly, explains the trade-off, and if an idea truly cannot be forged, it\n  says so too. Honesty is not a failure mode here; it is the standard.\n\n  Progress is tracked from 0% to 100%, every project is saved and restorable, and the final document exports cleanly to\n  Markdown.\n\n  ---\n  The philosophy behind the forge\n\n  IdeaForge was not built to make its creator a little smarter. It was built by a believer in technology who carries a\n  deeply human conviction: give a person a fish and they eat for a day; teach a person to fish and they eat for a\n  lifetime.\n\n  The real \"fish\" here is not any single product — it is the method. When a novice relies on a wizard who hands them the\n   answer, they remain a novice. When they are guided, step by step, through the thinking of a TRIZ master or a JTBD\n  practitioner, they slowly inherit a repeatable habit of rigorous innovation. The tool never hides its reasoning; it\n  shows its work, so that every user — student, founder, tinkerer — is not just receiving an answer, but quietly\n  learning to forge their own.\n\n  This is infrastructure for generosity: a forge that turns everyone's intuition into everyone's habit. The goal is not\n  one brilliant mind. The goal is a world where innovation is no longer a rare gift, but a common habit.",
    image: "/media/9b86b9f5-136d-410f-a676-f7d2c8398004.png",
    date: "July 2026",
    tags: ["Empowerment", "Methodology", "Synthesis", "Humanistic", "Democratization"],
    url: "https://idea-forge-orpin-xi.vercel.app/",
    source: "https://github.com",
    status: "published",
  },
  {
    id: "daily-photo-api",
    slug: "daily-photo-api",
    title: "Major Star Map (专业星图) — A Free Career Guidance Platform for Students",
    description: "Major Star Map is a public-interest educational platform built to help high school and college students understand\n  their academic and career future. Driven by a simple mission — every student deserves clear, honest guidance when\n  choosing a major — the site offers all of its core services completely free of charge.\n\n  What we offer:\n\n  - Complete major database: In-depth profiles for all 883 undergraduate majors under the Ministry of Education's 2026\n  catalog, covering curriculum, learning difficulty, salary ranges, recommended universities, and career directions.\n  - AI deep-analysis reports: Each major comes with a comprehensive report (career outlook, salary trends, graduate\n  school and civil service prospects, industry growth, AI impact, and a candid \"straight-talk\" review), generated by our\n   AI to give students data-backed insights instead of vague advice.\n  - Professional aptitude assessment: An interactive assessment that helps students discover which majors fit their\n  interests, abilities, and personality.\n  - Major comparison & career mapping: Tools to compare majors side by side and visualize career pathways across\n  industries.\n  - AI career-planning consultant: A specially built AI career-planning assistant — powered by our own skill system —\n  that answers students' questions about majors and career development free of charge, at any time.\n\n  Our goal is not commercial. It is to level the playing field: whether a student has access to expensive advisors or\n  not, everyone can get honest, professional, and free guidance about the road ahead.",
    image: "/media/e8b91432-adce-43cc-a106-d1847451c4a8.png",
    date: "September 8, 2025",
    tags: ["Free", "AI-powered", "Career Guidance", "883 Majors", "Data-driven"],
    url: "https://working-pass.vercel.app/",
    source: "",
    status: "published",
  }
];

export const publishedProjects: Project[] = projects.filter(p => p.status !== "draft");
